CONFIG += utf8_source
CONFIG += c++17
#conflict c++17 std::byte and window byte
DEFINES += _HAS_STD_BYTE=0

#warning
DEFINES += QT_DEPRECATED_WARNINGS
QMAKE_CFLAGS_WARN_ON = -W3
QMAKE_CXXFLAGS_WARN_ON = $$QMAKE_CFLAGS_WARN_ON
QMAKE_CXXFLAGS_WARN_ON += -we4100 -we4715 -we4189
QMAKE_CXXFLAGS += -sdl

#debug info
QMAKE_CFLAGS_RELEASE += -Zi
QMAKE_CXXFLAGS_RELEASE += -Zi
QMAKE_LFLAGS_RELEASE += /INCREMENTAL:NO /DEBUG
