/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4-78-g031c0cb0b4-20210701"
#endif /* AVUTIL_FFVERSION_H */
