/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.2-1-g8e98dfc57f-20220428"
#endif /* AVUTIL_FFVERSION_H */
